name: CI/CD Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Run linting
        run: npm run lint --if-present

      - name: Build project
        run: npm run build --if-present

  # Staging (for development branch) (Will prob be scraped later)
  deploy-staging:
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  # Production (for main branch)
  deploy-production:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
